Repository SURFnet/sp-dashboard, pull requests merged in 2021-02, with the labels that each got.

#394 Stop matching the Jira status to the entity status
  src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
Labels: 2.7, 2.8

#396 Remove oidcng restriction
  app/DoctrineMigrations/Version20210209152257.php
  app/config/config.yml
  app/config/parameters.yml.dist
  src/Surfnet/ServiceProviderDashboard/Application/Command/Service/CreateServiceCommand.php
  src/Surfnet/ServiceProviderDashboard/Application/Command/Service/EditServiceCommand.php
  src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/EditServiceCommandHandler.php
  src/Surfnet/ServiceProviderDashboard/Application/ViewObject/Manage/Config.php
  src/Surfnet/ServiceProviderDashboard/Application/ViewObject/Manage/ConfigFactory.php
  src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
  src/Surfnet/ServiceProviderDashboard/Domain/Service/OidcngEnabledMarshaller.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityEditController.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityResetSecretController.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/DependencyInjection/Configuration.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/ProtocolChoiceFactory.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Service/ServiceType.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Service/AuthorizationService.php
  tests/integration/Application/CommandHandler/Service/EditServiceCommandHandlerTest.php
  tests/unit/Infrastructure/DashboardBundle/Form/Entity/ProtocolChoiceFactoryTest.php
  tests/unit/Infrastructure/DashboardBundle/Service/AuthorizationServiceTest.php
Labels: 2.8

#368 Register required php extensions in composer.json
  composer.json
  composer.lock
Labels: 2.8

#397 Manage organization names
  app/DoctrineMigrations/Version20210211124755.php
  src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveEntityCommandInterface.php
  src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
  src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngResourceServerEntityCommand.php
  src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveSamlEntityCommand.php
  src/Surfnet/ServiceProviderDashboard/Application/Command/Service/CreateServiceCommand.php
  src/Surfnet/ServiceProviderDashboard/Application/Command/Service/EditServiceCommand.php
  src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveOidcngEntityCommandHandler.php
  src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveOidcngResourceServerEntityCommandHandler.php
  src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveSamlEntityCommandHandler.php
  src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/CreateServiceCommandHandler.php
  src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/EditServiceCommandHandler.php
  src/Surfnet/ServiceProviderDashboard/Application/Service/EntityMergeService.php
  src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/DataFixtures/ORM/WebTestFixtures.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngResourceServerEntityType.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/SamlEntityType.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Service/ServiceType.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
  tests/integration/Application/CommandHandler/Entity/SaveOidcngEntityCommandHandlerTest.php
  tests/integration/Application/CommandHandler/Entity/SaveOidcngResourceServerEntityCommandHandlerTest.php
  tests/integration/Application/CommandHandler/Service/CreateServiceCommandHandlerTest.php
  tests/integration/Application/CommandHandler/Service/EditServiceCommandHandlerTest.php
  tests/unit/Application/Service/EntityMergeServiceTest.php
  tests/webtests/EditServiceTest.php
  tests/webtests/ServiceCreateTest.php
Labels: 2.8

#404 Remove default scope from Oidcng RP entities
  src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngJsonGenerator.php
  src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/OidcngClient.php
  tests/unit/Application/Metadata/OidcngJsonGeneratorTest.php
  tests/unit/Application/Metadata/fixture/oidc10_rp_response.json
Labels: 2.8

#402 Remove trailing slashes from ClientID
  src/Surfnet/ServiceProviderDashboard/Application/Parser/OidcClientIdParser.php
  src/Surfnet/ServiceProviderDashboard/Application/Parser/OidcngClientIdParser.php
  tests/unit/Application/Parser/OidcngClientIdParserTest.php
Labels: 2.8

#399 Drop attribute constraint
  src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/ResetOidcSecretCommand.php
  src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
  src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveSamlEntityCommand.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Validator/Constraints/HasAttributes.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Validator/Constraints/HasAttributesValidator.php
  tests/integration/Infrastructure/DashboardBundle/Validator/Constraints/HasAttributesValidatorTest.php
  tests/webtests/EntityCreateSamlTest.php
Labels: 2.8

#405 Remove remaining OIDC crud
  tests/unit/Application/Metadata/JsonGeneratorStrategyTest.php
  tests/unit/Application/ViewObject/EntityTest.php
  tests/unit/Domain/Entity/Entity/ProtocolTest.php
Labels: 2.8

#403 Repair ParsleyJs by pinning JQ versions installed
  package.json
  yarn.lock
Labels: 2.8

#408 Adjust create new entity modal
  app/js/application.js
  app/js/components/service_add_entity.ts
  app/scss/components/modal_add_entity.scss
  app/scss/pages/base.scss
  src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityList.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/CreateNewEntityType.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityModal/addEntityModal.html.twig
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityType/type.html.twig
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/overview.html.twig
Labels: enhancement

#411 Ensure template has default choice
  app/js/components/service_add_entity.ts
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityModal/addEntityModal.html.twig
Labels: bug

#410 Ensure copy ClientId is editable
  src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
  src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngResourceServerEntityCommand.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Factory/EntityTypeFactory.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Factory/SaveCommandFactory.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Factory/SaveCommandFactoryInterface.php
Labels: bug

#414 Ensure typecheck for redirect url doesn't fail
  src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/OidcngClient.php
Labels: 2.8, bug
