Repository SURFnet/sp-dashboard, pull requests merged in 2021-03, with the labels that each got.

#420 Ensure attribute value is set on publishing entity
  src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/ArpGenerator.php
  src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/AttributeList.php
Labels: 2.8

#415 Add info fields to create entity titles
  app/scss/components/modal_add_entity.scss
  app/scss/components/tooltip.scss
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityModal/addEntityModal.html.twig
Labels: 2.8, enhancement

#417 Ensure redirect url is correct for copy action
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
Labels: 2.8, bug

#419 Consider closed and resolved status from Jira
  src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
  src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/Issue.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/DevelopmentIssueRepository.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/IssueRepository.php
  tests/unit/Domain/ValueObject/IssueCollectionTest.php
Labels: 2.8

#421 Refrain from overwriting Manage tracked attributes
  src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/ArpGenerator.php
  src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/AttributeList.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Factory/SaveCommandFactory.php
  tests/unit/Application/Metadata/JsonGenerator/ArpGeneratorTest.php
Labels: 2.8

#427 Make tooltip for test entity clickable
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityModal/addEntityModal.html.twig
Labels: 2.8, bug

#426 Show new production entity link for admins
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/overview.html.twig
Labels: 2.8, bug

#429 Ensure entity copy results in a new entity
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
Labels: 2.8, bug

#428 Ensure modal redirects correctly when submitted
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
Labels: 2.8, bug

#416 Fix custom redirect url validation
  app/js/components/validator_helper.test.ts
  app/js/components/validator_helper.ts
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Validator/Constraints/ValidRedirectUrlValidator.php
Labels: 2.8, bug

#431 Stop tracking scopes for resource servers
  src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngResourceServerJsonGenerator.php
  src/Surfnet/ServiceProviderDashboard/Application/Service/EntityMergeService.php
  src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/OidcClientInterface.php
  src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/OidcngClient.php
  src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/OidcngResourceServerClient.php
  tests/unit/Application/Metadata/OidcngResourceServerJsonGeneratorTest.php
Labels: 2.8

#430 Hide content of tooltip
  app/scss/components/tooltip.scss
Labels: 2.8, bug

#432 Remove form validation from CreateNewEntityType form
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityModal/addEntityModal.html.twig
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityType/type.html.twig
Labels: 2.8, bug
