Repository SURFnet/sp-dashboard, pull requests merged in 2021-05, with the labels that each got.

#450 Ensure that copied entities have a clear ACL
  src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/AllowedIdentityProviders.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
Labels: bug

#449 Ensure all attributes are shown on view
  src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityDetail.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detail.html.twig
Labels: bug

#451 Ensure attributes are validated also on test
  src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
  src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveSamlEntityCommand.php
Labels: bug

#448 Remove organizationName leftover
  src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/LoadMetadataCommandHandler.php
Labels: bug

#452 Prevent calling count on null
  src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/IssueCollection.php
  tests/unit/Domain/ValueObject/IssueCollectionTest.php
Labels: bug

#455 Add release documentation to dev docs
  docs/index.md
  docs/release.md
Labels: enhancement

#460 Show the correct descriptions per language
  src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityDetail.php
Labels: 3.2, bug

#461 Hide edit for PE on removal requested
  src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityActions.php
  src/Surfnet/ServiceProviderDashboard/Domain/Entity/ManageEntity.php
  tests/integration/Application/ViewObject/EntityActionsTest.php
Labels: 3.2, bug

#463 Ensure name in En/Nl is mandatory
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OauthClientCredentialEntityType.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngResourceServerEntityType.php
  src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/SamlEntityType.php
Labels: 3.2, enhancement
